<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUJ6Mjfk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJ6Mjfk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJ6Mjfk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUJ6Mjfk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUJ6Mjfk\App_KernelDevDebugContainer([
    'container.build_hash' => 'UJ6Mjfk',
    'container.build_id' => '41b421b9',
    'container.build_time' => 1690357842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJ6Mjfk');
