<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Rnxvgs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Rnxvgs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1Rnxvgs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1Rnxvgs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1Rnxvgs\App_KernelDevDebugContainer([
    'container.build_hash' => '1Rnxvgs',
    'container.build_id' => '5f9e0158',
    'container.build_time' => 1690291752,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Rnxvgs');
